
server:
  port: 8100
  
spring:  
  h2:
    console:
      enabled: true
      path: /console
      
  thymeleaf:
    cache: false
    
  datasource:
    url: jdbc:h2:mem:tacocloud
    generate-unique-name: false
    name: tacocloud
    driverClassName: org.h2.Driver
    username: sa
    password: 
